import type { Metadata } from "next";
import { Marcellus, DM_Sans, DM_Mono } from "next/font/google";
import "./globals.css";

const marcellus = Marcellus({ 
  weight: "400",
  subsets: ['latin'],
  variable: "--font-marcellus"
});

const dm_sans = DM_Sans({ 
  weight: ["300", "400", "500", "700"],
  subsets: ['latin'],
  variable: "--font-dm_sans"
});

const dm_mono = DM_Mono({ 
  weight: "400",
  subsets: ['latin'],
  variable: "--font-dm_mono"
});

export const metadata: Metadata = {
  title: "Reformer | Wellness Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${marcellus.variable} ${dm_sans.variable} ${dm_mono.variable}`}>
        {children}
      </body>
    </html>
  );
}
